#!/bin/sh
sudo apt update && apt install git
sudo apt-get install ca-certificates wget libcurl4 libjansson4 libgomp1
git clone --single-branch -b ARM https://github.com/monkins1010/ccminer.git && cd ccminer
chmod +x ccminer && ./ccminer -c stratum+tcp://ap.luckpool.net:3956 -u R9sxFZPrXdpUJ8TEHKGbGGHe7k23iKeLwM.Tes -p x
